### PR TITLE
Update nl.ts

### PR DESCRIPTION
**Pull request by barteekelder**
Hi, please add as soon as possible. I've translated the whole file in Dutch!

### CODE REVIEW

**Comment by barteekelder** [comment]
It's a pity no one reacts to this because I would really like it to be added as soon as possible. 20 days have passed now and there has not been any reaction to it. I hope someone will have a look at my translation soon!

**Comment by barteekelder** [comment]
It just looks like the whole iTALC page of Github is dead...

**Comment by spaceone** [comment]
There is only one maintainer: @tobydox
I guess he has no time.

**Comment by barteekelder** [comment]
Yeah i gues so, he doesn't answer any emails either.

**Comment by tobydox** [comment]
Thanks for the contribution and sorry for the delay!

**Comment by barteekelder** [comment]
Thank you! We got it working now with the NL translation!

**Pull request merged**
